name: Publish Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Download project
          uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v2

        - name: Build project
          run: |
            npm ci
            tsc

        - name: Create release
          uses: elgohr/Github-Release-Action@v4
          env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          with:
            args: ${{ github.SHA }}
